export const fetchNovel = async (req, res) => {
  try {
    // Example hardcoded data; in a real scenario, fetch this from a database
    const novels = [
      {
        id: 6,
        title: "Marvel's Spider-Man: Miles Morales – Wings of Fury",
        author: "Brittney Morris",
        publication: "2020-11-10T00:00:00+08:00",
        genre: "Superhero",
        ratings: 8,
        summary:
          '<html><head></head><body><p class="text-p"><em>Marvel’s Spider-Man: Miles Morales – Wings of Fury</em> explores the early days of Miles Morales as he begins to take on more responsibility as a superhero. The novel takes place before the events of the video game, providing valuable context for fans of the game and giving more depth to Miles\' journey.</p><p class="text-p">The story opens with Miles still adjusting to his new role as the Spider-Man of Harlem, learning to balance his superhero duties with his personal life. His mentor, Peter Parker, has been guiding him, but Peter is about to leave town for a short period, leaving Miles to handle things on his own.</p><p class="text-p">As Miles steps into the role of Harlem\'s protector, he faces a new threat: Adrian Toomes, also known as the Vulture, and his daughter Starling. Both are stirring up trouble in New York, with Toomes being a long-established villain and Starling proving to be a formidable foe in her own right. The Vulture is orchestrating a plan to release a dangerous new technology that could have catastrophic consequences for the city.</p><p class="text-p">As Miles juggles his responsibilities, he learns that being Spider-Man is about more than just fighting bad guys. It\'s about understanding the consequences of his actions, protecting those he loves, and ensuring that the people of Harlem are safe. Throughout the novel, Miles is tested, both physically and emotionally. He grapples with self-doubt, wondering if he has what it takes to live up to Peter Parker\'s legacy, but he also grows more confident in his abilities.</p><p class="text-p">The relationship between Miles and Starling adds an interesting dynamic to the story. Starling is a complex character with her own motivations, making her more than just another villain for Miles to face. Her connection to Vulture adds emotional weight to the conflict, as she struggles with the legacy of her family while Miles faces the legacy of being the next Spider-Man.</p><p class="text-p"><strong class="text-strong">Themes</strong>:</p><ul><li><p class="text-p"><strong class="text-strong">Legacy</strong>: A key theme in <em>Wings of Fury</em> is Miles’ struggle to live up to the Spider-Man mantle that Peter Parker has left behind. The novel explores what it means to carry the weight of such a legacy and how Miles has to forge his own path.</p></li><li><p class="text-p"><strong class="text-strong">Responsibility</strong>: Much like the classic Spider-Man mantra, “With great power comes great responsibility,” Miles learns what it means to be responsible for the safety of his neighborhood, the people he loves, and the city at large.</p></li><li><p class="text-p"><strong class="text-strong">Self-Discovery</strong>: Throughout the novel, Miles is on a journey of self-discovery, learning to trust himself and grow into his role as Spider-Man. He battles self-doubt but also learns to have confidence in his abilities.</p></li></ul><p class="text-p"><strong class="text-strong">Connections to the Game</strong>:</p><ul><li><p class="text-p"><em>Wings of Fury</em> serves as a prequel to the <em>Marvel\'s Spider-Man: Miles Morales</em> video game, giving fans an in-depth look at the challenges Miles faces before the game’s events.</p></li><li><p class="text-p">The novel deepens the backstory of the characters, including Vulture and Starling, making their appearance in the game more meaningful for those who have read the book.</p></li></ul><p class="text-p"><strong class="text-strong">Impact</strong>:</p><ul><li><p class="text-p">The novel provides an emotional and action-packed look into Miles’ early days as Spider-Man, expanding on his character development in a way that complements the video game.</p></li><li><p class="text-p">Fans of both the comic book version of Miles Morales and the game will enjoy seeing how his character is portrayed as a young hero trying to find his footing.</p></li></ul></body></html>',
        cover: {
          id: 19,
          name: "2919293.jpg",
          alternativeText: null,
          caption: null,
          width: 640,
          height: "1970-01-01T07:30:01+07:30",
          formats: {
            small: {
              ext: ".jpg",
              url: "/uploads/small_2919293_ac8c26838b.jpg",
              hash: "small_2919293_ac8c26838b",
              mime: "image/jpeg",
              name: "small_2919293.jpg",
              path: null,
              size: 36.93,
              width: 320,
              height: 500,
              sizeInBytes: 36932,
            },
            medium: {
              ext: ".jpg",
              url: "/uploads/medium_2919293_ac8c26838b.jpg",
              hash: "medium_2919293_ac8c26838b",
              mime: "image/jpeg",
              name: "medium_2919293.jpg",
              path: null,
              size: 73,
              width: 480,
              height: 750,
              sizeInBytes: 72996,
            },
            thumbnail: {
              ext: ".jpg",
              url: "/uploads/thumbnail_2919293_ac8c26838b.jpg",
              hash: "thumbnail_2919293_ac8c26838b",
              mime: "image/jpeg",
              name: "thumbnail_2919293.jpg",
              path: null,
              size: 5.25,
              width: 100,
              height: 156,
              sizeInBytes: "1970-01-01T07:30:05+07:30",
            },
          },
          hash: "2919293_ac8c26838b",
          ext: ".jpg",
          mime: "image/jpeg",
          size: 94.01,
          url: "/uploads/2919293_ac8c26838b.jpg",
          previewUrl: null,
          provider: "local",
          provider_metadata: null,
          folderPath: "/",
        },
      },
      {
        id: 12,
        title: "Jujutsu Kaisen",
        author: "Gege Akutami",
        publication: "2018-03-01T00:00:00+08:00",
        genre: "Dark Fantasy",
        ratings: 9,
        summary:
          '<html><head></head><body><p class="text-p"><strong class="text-strong">"Jujutsu Kaisen"</strong> follows <strong class="text-strong">Yuji Itadori</strong>, a high school student with extraordinary physical abilities who leads a relatively normal life until he encounters a cursed object. When Yuji\'s friends unseal this object, it turns out to be a rotting finger belonging to a powerful curse named <strong class="text-strong">Ryomen Sukuna</strong>. This act unleashes Sukuna, leading to the world of curses and jujutsu sorcery being thrust into Yuji’s life.</p><p class="text-p">To protect his friends and deal with the aftermath, Yuji swallows the cursed finger, becoming the host for Sukuna. As a result, he is introduced to the world of jujutsu sorcery by <strong class="text-strong">Satoru Gojo</strong>, a teacher at the Tokyo Metropolitan Jujutsu Technical School. This school trains students to combat curses—malevolent supernatural entities born from human negative emotions.</p><p class="text-p">Key arcs in the series include:</p><ul><li><p class="text-p"><strong class="text-strong">The Tokyo Metropolitan Curse Technical School Arc</strong>: Yuji enrolls in the school and meets other students like <strong class="text-strong">Megumi Fushiguro</strong> and <strong class="text-strong">Nobara Kugisaki</strong>. They are trained in the art of jujutsu and face off against various curses in their initial missions.</p></li><li><p class="text-p"><strong class="text-strong">The Curse Womb Must Die Arc</strong>: The students confront a powerful curse that emerges from a sealed location, leading to intense battles and the introduction of new characters.</p></li><li><p class="text-p"><strong class="text-strong">The Kyoto Goodwill Event Arc</strong>: A friendly competition between Tokyo and Kyoto jujutsu schools turns deadly when a group of curses attacks, leading to significant character development and new alliances.</p></li><li><p class="text-p"><strong class="text-strong">The Shibuya Incident Arc</strong>: A major arc where curses launch a large-scale attack on Tokyo during the Shibuya Festival. This arc is pivotal, revealing more about Sukuna’s intentions, the nature of curses, and the deeper complexities of jujutsu sorcery.</p></li><li><p class="text-p"><strong class="text-strong">The Culling Game Arc</strong>: The story shifts to a new conflict involving a deadly game organized by a curse user, with high stakes and intense battles as Yuji and his allies try to survive and uncover the truth behind the game.</p></li></ul><p class="text-p">"Jujutsu Kaisen" is known for its innovative and engaging combat sequences, unique curse abilities, and strong character development. It combines horror elements with action-packed scenes and explores themes of life, death, and the impact of human emotions on the supernatural world.</p><p class="text-p">The series has gained widespread popularity for its compelling narrative and dynamic artwork, making it a standout in contemporary shōnen manga and anime.</p></body></html>',
        cover: {
          id: 25,
          name: "823894982.jpg",
          alternativeText: null,
          caption: null,
          width: "1970-01-01T07:30:01+07:30",
          height: "1970-01-01T07:30:02+07:30",
          formats: {
            large: {
              ext: ".jpg",
              url: "/uploads/large_823894982_bb23ecf505.jpg",
              hash: "large_823894982_bb23ecf505",
              mime: "image/jpeg",
              name: "large_823894982.jpg",
              path: null,
              size: 93.98,
              width: 636,
              height: "1970-01-01T07:30:01+07:30",
              sizeInBytes: 93977,
            },
            small: {
              ext: ".jpg",
              url: "/uploads/small_823894982_bb23ecf505.jpg",
              hash: "small_823894982_bb23ecf505",
              mime: "image/jpeg",
              name: "small_823894982.jpg",
              path: null,
              size: 30.55,
              width: 318,
              height: 500,
              sizeInBytes: 30545,
            },
            medium: {
              ext: ".jpg",
              url: "/uploads/medium_823894982_bb23ecf505.jpg",
              hash: "medium_823894982_bb23ecf505",
              mime: "image/jpeg",
              name: "medium_823894982.jpg",
              path: null,
              size: 59.22,
              width: 477,
              height: 750,
              sizeInBytes: 59216,
            },
            thumbnail: {
              ext: ".jpg",
              url: "/uploads/thumbnail_823894982_bb23ecf505.jpg",
              hash: "thumbnail_823894982_bb23ecf505",
              mime: "image/jpeg",
              name: "thumbnail_823894982.jpg",
              path: null,
              size: 4.8,
              width: 99,
              height: 156,
              sizeInBytes: "1970-01-01T07:30:04+07:30",
            },
          },
          hash: "823894982_bb23ecf505",
          ext: ".jpg",
          mime: "image/jpeg",
          size: 343.65,
          url: "/uploads/823894982_bb23ecf505.jpg",
          previewUrl: null,
          provider: "local",
          provider_metadata: null,
          folderPath: "/",
        },
      },
      {
        id: 3,
        title: "Your Name (Kimi no Na wa)",
        author: "Makoto Shinkai",
        publication: "2016-06-18T00:00:00+08:00",
        genre: "Romance",
        ratings: 9,
        summary:
          '<html><head></head><body><p class="text-p"><strong class="text-strong">"Your Name"</strong> tells the story of two high school students, Taki Tachibana and Mitsuha Miyamizu, who mysteriously begin to switch bodies and experience each other\'s lives. Mitsuha lives in the rural town of Itomori, where she feels trapped and yearns for the excitement of city life. Taki, on the other hand, is a city boy living in Tokyo, balancing his time between school and his part-time job at a restaurant.</p><p class="text-p">One day, the two wake up to realize they have swapped bodies. Confused but intrigued, they begin to communicate with each other by leaving notes, texts, and messages on their phones or writing on their bodies. As they live each other’s lives intermittently, they form a unique bond despite never meeting in person. Their relationship grows as they navigate the challenges of the body-swap phenomenon, helping each other deal with personal issues in their respective lives.</p><p class="text-p">However, just as they start to get closer, the body-swapping suddenly stops. Taki, desperate to meet Mitsuha, embarks on a journey to find her. His search leads him to discover a shocking truth: Itomori, Mitsuha’s town, was destroyed three years ago by a comet strike. Mitsuha, along with many other townspeople, perished in the disaster.</p><p class="text-p">Devastated but determined, Taki decides to alter fate by traveling to Itomori in the past, using the body-swap connection to warn Mitsuha and save the town. In an emotional climax, the two finally meet during twilight, a brief moment where the boundary between their worlds is blurred. Despite the challenges of time and memory, Taki manages to give Mitsuha the knowledge she needs to evacuate the town before the comet hits.</p><p class="text-p">After altering history and preventing the disaster, the two lose their memories of each other, but they retain a deep, inexplicable sense of longing. Years later, as young adults, they cross paths in Tokyo, seemingly drawn to each other by a bond they can’t fully remember. In the film\'s final moment, they stop, turn, and ask each other, "Have we met before?"</p><p class="text-p">"Your Name" is a powerful tale of fate, time, and connection. It explores themes of longing, the desire for a different life, and the bittersweetness of love transcending time and space. The film’s stunning animation, rich emotional depth, and unforgettable score by RADWIMPS helped it become a massive success globally, resonating with audiences of all ages."</p><p class="text-p">The movie became a cultural phenomenon and was praised for its beautiful animation, emotional storytelling, and its intricate exploration of fate and memory.</p></body></html>',
        cover: {
          id: 16,
          name: "293842.jpg",
          alternativeText: null,
          caption: null,
          width: 703,
          height: "1970-01-01T07:30:01+07:30",
          formats: {
            small: {
              ext: ".jpg",
              url: "/uploads/small_293842_65b037885b.jpg",
              hash: "small_293842_65b037885b",
              mime: "image/jpeg",
              name: "small_293842.jpg",
              path: null,
              size: 38.59,
              width: 352,
              height: 500,
              sizeInBytes: 38594,
            },
            medium: {
              ext: ".jpg",
              url: "/uploads/medium_293842_65b037885b.jpg",
              hash: "medium_293842_65b037885b",
              mime: "image/jpeg",
              name: "medium_293842.jpg",
              path: null,
              size: 73.27,
              width: 527,
              height: 750,
              sizeInBytes: 73268,
            },
            thumbnail: {
              ext: ".jpg",
              url: "/uploads/thumbnail_293842_65b037885b.jpg",
              hash: "thumbnail_293842_65b037885b",
              mime: "image/jpeg",
              name: "thumbnail_293842.jpg",
              path: null,
              size: 5.99,
              width: 109,
              height: 156,
              sizeInBytes: "1970-01-01T07:30:05+07:30",
            },
          },
          hash: "293842_65b037885b",
          ext: ".jpg",
          mime: "image/jpeg",
          size: 115.91,
          url: "/uploads/293842_65b037885b.jpg",
          previewUrl: null,
          provider: "local",
          provider_metadata: null,
          folderPath: "/",
        },
      },
      {
        id: 1,
        title: "Demon Slayer: Kimetsu no Yaiba",
        author: "Koyoharu Gotouge",
        publication: "2016-02-01T00:00:00+08:00",
        genre: "Action",
        ratings: 8,
        summary:
          '<html><head></head><body><p class="text-p">Set during Japan’s Taisho period (1912-1926), <strong class="text-strong">"Demon Slayer: Kimetsu no Yaiba"</strong> tells the story of a young boy named <strong class="text-strong">Tanjiro Kamado</strong>, who lives in the mountains with his impoverished family. Tanjiro is the eldest of several siblings and the primary breadwinner after his father’s death, making frequent trips to the nearby village to sell charcoal.</p><p class="text-p">One day, after spending the night in the village, Tanjiro returns home to a horrifying scene—his entire family has been brutally slaughtered by demons, and his younger sister, <strong class="text-strong">Nezuko</strong>, is the only survivor, but she has been transformed into a demon. However, unlike typical demons, Nezuko retains some of her human emotions and shows signs of protecting her brother rather than harming him.</p><p class="text-p">Heartbroken but determined, Tanjiro embarks on a quest to find a cure for Nezuko and avenge his family by joining the <strong class="text-strong">Demon Slayer Corps</strong>, a secret organization of elite warriors trained to hunt down demons. Along his journey, he encounters several skilled allies, including the brash but kind-hearted <strong class="text-strong">Zenitsu Agatsuma</strong>, who uses lightning-based techniques, and the wild but loyal <strong class="text-strong">Inosuke Hashibira</strong>, a boar-masked fighter with enhanced physical abilities. Together, they face numerous challenges, including powerful demons known as the <strong class="text-strong">Twelve Kizuki</strong>, the upper echelons of demon society, who serve under the main antagonist, <strong class="text-strong">Muzan Kibutsuji</strong>, the original and most powerful demon responsible for the slaughter of Tanjiro’s family.</p><p class="text-p">As Tanjiro and his friends face increasingly powerful foes, they undergo intense physical and emotional training. Tanjiro also learns special swordsmanship techniques known as <strong class="text-strong">Breathing Styles</strong>, specifically mastering the <strong class="text-strong">Water Breathing</strong> and later the elusive <strong class="text-strong">Sun Breathing</strong>, an ancient technique that holds the key to defeating Muzan.</p><p class="text-p">The story is not just about the battles between humans and demons but also delves into the tragic pasts of both the demons and the slayers, revealing that many demons were once humans with their own hopes, dreams, and struggles. Despite the carnage they have caused, Tanjiro often shows compassion for his enemies, recognizing the humanity they once possessed.</p><p class="text-p">As the plot progresses, Tanjiro’s pursuit of Muzan grows more intense, and the stakes become higher as the Demon Slayer Corps prepares for the ultimate confrontation. Throughout this journey, Tanjiro’s unwavering kindness and perseverance are central themes, as he fights not just to protect the world from demons but also to restore his sister\'s humanity.</p><p class="text-p">The manga explores themes of grief, loss, the bond between siblings, and the struggle between good and evil, blending fast-paced action with emotional depth, making it a fan-favorite across the globe.</p></body></html>',
        cover: {
          id: 14,
          name: "992384.jpeg",
          alternativeText: null,
          caption: null,
          width: 666,
          height: "1970-01-01T07:30:01+07:30",
          formats: {
            small: {
              ext: ".jpeg",
              url: "/uploads/small_992384_139a06bd87.jpeg",
              hash: "small_992384_139a06bd87",
              mime: "image/jpeg",
              name: "small_992384.jpeg",
              path: null,
              size: 61.43,
              width: 333,
              height: 500,
              sizeInBytes: 61428,
            },
            medium: {
              ext: ".jpeg",
              url: "/uploads/medium_992384_139a06bd87.jpeg",
              hash: "medium_992384_139a06bd87",
              mime: "image/jpeg",
              name: "medium_992384.jpeg",
              path: null,
              size: 118.51,
              width: 500,
              height: 750,
              sizeInBytes: 118514,
            },
            thumbnail: {
              ext: ".jpeg",
              url: "/uploads/thumbnail_992384_139a06bd87.jpeg",
              hash: "thumbnail_992384_139a06bd87",
              mime: "image/jpeg",
              name: "thumbnail_992384.jpeg",
              path: null,
              size: 8.28,
              width: 104,
              height: 156,
              sizeInBytes: "1970-01-01T07:30:08+07:30",
            },
          },
          hash: "992384_139a06bd87",
          ext: ".jpeg",
          mime: "image/jpeg",
          size: 193.54,
          url: "/uploads/992384_139a06bd87.jpeg",
          previewUrl: null,
          provider: "local",
          provider_metadata: null,
          folderPath: "/",
        },
      },
      {
        id: 10,
        title: "Boruto: Naruto Next Generations",
        author: "Masashi Kishimoto",
        publication: "2016-01-01T00:00:00+08:00",
        genre: "Action",
        ratings: 7,
        summary:
          '<html><head></head><body><p class="text-p"><strong class="text-strong">"Boruto: Naruto Next Generations"</strong> takes place several years after the events of "Naruto: Shippuden." The story focuses on <strong class="text-strong">Boruto Uzumaki</strong>, the son of Naruto Uzumaki, who is now the Seventh Hokage of Konohagakure. Boruto’s life as the son of the Hokage is marked by a mix of privilege and pressure, as he struggles to find his own path separate from his father\'s legacy.</p><p class="text-p">The series explores Boruto’s journey as a young ninja navigating his role in a more modernized and peaceful world. Despite the absence of major wars, new threats emerge, and Boruto and his friends must face these challenges while dealing with their own personal issues and ambitions.</p><p class="text-p">Key arcs in the series include:</p><ul><li><p class="text-p"><strong class="text-strong">Introduction of Boruto and His Team</strong>: Boruto teams up with Sarada Uchiha, the daughter of Sasuke Uchiha, and Mitsuki, an artificial human created by Orochimaru. Together, they undertake missions and face various trials.</p></li><li><p class="text-p"><strong class="text-strong">The Chūnin Exams</strong>: This arc revisits the traditional ninja exams, with Boruto and his peers participating in the Chūnin Exams, which lead to dramatic and dangerous events that test their abilities and resolve.</p></li><li><p class="text-p"><strong class="text-strong">The Kinshiki and Momoshiki Arcs</strong>: The series introduces powerful enemies from another dimension, Kinshiki and Momoshiki Ōtsutsuki, who pose a significant threat to the ninja world. The arcs explore their motives and the impact on Boruto’s world.</p></li><li><p class="text-p"><strong class="text-strong">The Kara Organization</strong>: A secretive and dangerous organization emerges, led by <strong class="text-strong">Jigen</strong> and later <strong class="text-strong">Isshiki Ōtsutsuki</strong>. Their dark ambitions challenge Boruto and his friends, leading to intense confrontations and significant developments in the series.</p></li></ul><p class="text-p">Throughout "Boruto: Naruto Next Generations," themes of legacy, self-discovery, and the challenges of growing up are explored. Boruto grapples with his father’s shadow, his own desires, and the responsibilities of being a ninja. The series expands on the "Naruto" universe, introducing new characters, technologies, and conflicts while maintaining connections to its predecessor.</p><p class="text-p">Overall, "Boruto: Naruto Next Generations" continues the legacy of the original series, offering fans a fresh perspective on the next generation of ninjas while building on the rich world created by Masashi Kishimoto.</p></body></html>',
        cover: {
          id: 23,
          name: "283819.jpg",
          alternativeText: null,
          caption: null,
          width: 611,
          height: 960,
          formats: {
            small: {
              ext: ".jpg",
              url: "/uploads/small_283819_16d08ec484.jpg",
              hash: "small_283819_16d08ec484",
              mime: "image/jpeg",
              name: "small_283819.jpg",
              path: null,
              size: 56.8,
              width: 318,
              height: 500,
              sizeInBytes: 56800,
            },
            medium: {
              ext: ".jpg",
              url: "/uploads/medium_283819_16d08ec484.jpg",
              hash: "medium_283819_16d08ec484",
              mime: "image/jpeg",
              name: "medium_283819.jpg",
              path: null,
              size: 108.52,
              width: 477,
              height: 750,
              sizeInBytes: 108519,
            },
            thumbnail: {
              ext: ".jpg",
              url: "/uploads/thumbnail_283819_16d08ec484.jpg",
              hash: "thumbnail_283819_16d08ec484",
              mime: "image/jpeg",
              name: "thumbnail_283819.jpg",
              path: null,
              size: 7.7,
              width: 99,
              height: 156,
              sizeInBytes: "1970-01-01T07:30:07+07:30",
            },
          },
          hash: "283819_16d08ec484",
          ext: ".jpg",
          mime: "image/jpeg",
          size: 158.04,
          url: "/uploads/283819_16d08ec484.jpg",
          previewUrl: null,
          provider: "local",
          provider_metadata: null,
          folderPath: "/",
        },
      },
      {
        id: 4,
        title: "A Silent Voice (Koe no Katachi)",
        author: "Yoshitoki Ōima",
        publication: "2013-08-01T00:00:00+08:00",
        genre: "Drama",
        ratings: 7,
        summary:
          '<html><head></head><body><p class="text-p"><strong class="text-strong">"A Silent Voice"</strong> tells a poignant and emotional story about bullying, guilt, redemption, and the struggle for forgiveness. The plot centers around Shoya Ishida, a boy who, during elementary school, mercilessly bullied Shoko Nishimiya, a deaf girl who transferred to his class. Shoko, who struggles to communicate using sign language and a notebook, becomes the target of Shoya and his classmates\' cruel teasing due to her disability. The relentless bullying eventually forces Shoko to transfer to another school.</p><p class="text-p">However, the tables turn when Shoya’s actions are exposed, and he himself becomes ostracized and bullied by his peers. Left friendless and consumed by guilt, Shoya grows up isolated, haunted by the memories of what he did. As he reaches high school, Shoya is deeply depressed, filled with self-loathing, and contemplates suicide, seeing no future for himself.</p><p class="text-p">At this point, Shoya decides to seek redemption by finding Shoko and apologizing for his past actions. He tracks her down and learns that, despite her suffering, she harbors no ill will toward him. Over time, the two begin to develop an unlikely friendship, with Shoya learning sign language to better communicate with Shoko. Shoya, who once made Shoko’s life miserable, now strives to help her connect with others and overcome her own feelings of inadequacy.</p><p class="text-p">As Shoya reconnects with Shoko, he also slowly begins to rebuild relationships with others, including old classmates and new friends. However, the weight of the past still looms large, as the characters must confront their feelings of guilt, trauma, and the consequences of their actions. The film delves into the complex emotions of both the victim and the perpetrator of bullying, highlighting how both parties can carry scars from the experience.</p><p class="text-p">The climax of the film is an emotional and raw exploration of Shoya’s journey toward self-forgiveness and acceptance. He comes to realize that while seeking forgiveness from others is important, forgiving oneself is equally crucial. His bond with Shoko deepens as they both struggle with feelings of self-worth and the need for connection, culminating in a powerful message about healing and the importance of understanding.</p><p class="text-p">In the final scenes, Shoya finally begins to open up to those around him, learning to see the world again and connect with people in a meaningful way. He removes the metaphorical "X" marks that he had placed over people’s faces, a visual representation of his self-imposed isolation, symbolizing his newfound ability to accept others and himself.</p><p class="text-p"><strong class="text-strong">Themes</strong>: "A Silent Voice" tackles several deep and universal themes, including:</p><ul><li><p class="text-p"><strong class="text-strong">Bullying</strong>: The devastating effects it can have on both the victim and the perpetrator.</p></li><li><p class="text-p"><strong class="text-strong">Disability</strong>: Shoko’s struggle as a deaf person in a world that often fails to understand or accommodate her needs.</p></li><li><p class="text-p"><strong class="text-strong">Mental Health</strong>: Shoya’s battle with depression, guilt, and suicidal thoughts is portrayed with emotional depth.</p></li><li><p class="text-p"><strong class="text-strong">Redemption and Forgiveness</strong>: Shoya’s quest for redemption forms the emotional core of the story, illustrating how healing requires both seeking forgiveness from others and forgiving oneself.</p></li></ul><p class="text-p">"A Silent Voice" is renowned for its sensitive portrayal of complex emotional and social issues, stunning animation, and its emphasis on empathy and understanding. The film’s nuanced storytelling and breathtaking visuals, accompanied by an evocative score by Kensuke Ushio, earned it critical acclaim and resonated deeply with audiences worldwide."</p><p class="text-p">The film highlights the power of kindness, the difficulty of self-forgiveness, and the importance of second chances, making it a profound and moving experience.</p></body></html>',
        cover: {
          id: 17,
          name: "992839.jpg",
          alternativeText: null,
          caption: null,
          width: 400,
          height: 600,
          formats: {
            small: {
              ext: ".jpg",
              url: "/uploads/small_992839_5a489fc07e.jpg",
              hash: "small_992839_5a489fc07e",
              mime: "image/jpeg",
              name: "small_992839.jpg",
              path: null,
              size: 55.95,
              width: 333,
              height: 500,
              sizeInBytes: 55948,
            },
            thumbnail: {
              ext: ".jpg",
              url: "/uploads/thumbnail_992839_5a489fc07e.jpg",
              hash: "thumbnail_992839_5a489fc07e",
              mime: "image/jpeg",
              name: "thumbnail_992839.jpg",
              path: null,
              size: 6.79,
              width: 104,
              height: 156,
              sizeInBytes: "1970-01-01T07:30:06+07:30",
            },
          },
          hash: "992839_5a489fc07e",
          ext: ".jpg",
          mime: "image/jpeg",
          size: 71.78,
          url: "/uploads/992839_5a489fc07e.jpg",
          previewUrl: null,
          provider: "local",
          provider_metadata: null,
          folderPath: "/",
        },
      },
      {
        id: 2,
        title: "No Game No Life",
        author: "Yuu Kamiya",
        publication: "2012-04-25T00:00:00+08:00",
        genre: "Fantasy",
        ratings: 8,
        summary:
          '<html><head></head><body><p class="text-p"><strong class="text-strong">"No Game No Life"</strong> revolves around two siblings, Sora and Shiro, who are unbeatable gamers in the world of online gaming. They view reality as just another boring game. Known as the legendary gaming duo "Blank," they leave an impression of invincibility, never losing a single game. One day, after defeating a mysterious challenger in an online chess match, the siblings are summoned to a strange, alternate world by a god named Tet.</p><p class="text-p">In this new world, called Disboard, everything is determined by games. This includes the fate of nations, the social hierarchy, and even life itself. The ten governing rules prohibit violence, war, or crime, making all disputes resolved through games, with the outcome binding all parties involved. Sora and Shiro, now more engaged than ever, must navigate through this world where intelligence, strategy, and manipulation hold more weight than brute force. They quickly set their sights on conquering this realm, challenging powerful races and nations with their masterful understanding of games and psychology.</p><p class="text-p">As the series progresses, Sora and Shiro build alliances, face off against formidable opponents, and challenge the highest stakes games, all while uncovering the mysteries of Disboard and aiming to challenge the god Tet in an ultimate game for control of the world.</p><p class="text-p">"No Game No Life" is not just about battles of wits but also the deeper exploration of human desires, identity, and existential freedom. With themes of teamwork, self-worth, and the limits of one\'s capabilities, the series delves into profound psychological aspects through its fantasy setting. The dynamic between Sora and Shiro as co-dependent siblings provides a central emotional core, balancing out the grand world-building and tactical games they encounter."</p><p class="text-p">The series stands out for its vibrant, colorful art style, intelligent and engaging game mechanics, and the unique world where games dictate everything. It has been well received, particularly for its bold, strategic narrative approach and detailed world.</p></body></html>',
        cover: {
          id: 15,
          name: "891293.jpg",
          alternativeText: null,
          caption: null,
          width: 353,
          height: 503,
          formats: {
            small: {
              ext: ".jpg",
              url: "/uploads/small_891293_a7e8c980bf.jpg",
              hash: "small_891293_a7e8c980bf",
              mime: "image/jpeg",
              name: "small_891293.jpg",
              path: null,
              size: 55.89,
              width: 351,
              height: 500,
              sizeInBytes: 55887,
            },
            thumbnail: {
              ext: ".jpg",
              url: "/uploads/thumbnail_891293_a7e8c980bf.jpg",
              hash: "thumbnail_891293_a7e8c980bf",
              mime: "image/jpeg",
              name: "thumbnail_891293.jpg",
              path: null,
              size: 7.65,
              width: 109,
              height: 156,
              sizeInBytes: "1970-01-01T07:30:07+07:30",
            },
          },
          hash: "891293_a7e8c980bf",
          ext: ".jpg",
          mime: "image/jpeg",
          size: 57.56,
          url: "/uploads/891293_a7e8c980bf.jpg",
          previewUrl: null,
          provider: "local",
          provider_metadata: null,
          folderPath: "/",
        },
      },
      {
        id: 11,
        title: "Attack on Titan",
        author: "Hajime Isayama",
        publication: "2009-01-01T00:00:00+08:00",
        genre: "Dark Fantasy",
        ratings: 9,
        summary:
          '<html><head></head><body><p class="text-p"><strong class="text-strong">"Attack on Titan"</strong> is set in a world where humanity is on the brink of extinction due to giant humanoid creatures known as Titans. These Titans have driven the remnants of humanity into a series of walled cities designed to protect them from the Titans\' attacks.</p><p class="text-p">The story follows <strong class="text-strong">Eren Yeager</strong>, his adoptive sister <strong class="text-strong">Mikasa Ackerman</strong>, and their friend <strong class="text-strong">Armin Arlert</strong>, who join the military to fight against the Titans after their city is destroyed and Eren’s mother is killed by a Titan. They are driven by a desire for revenge and a quest for freedom from the confines of their walled existence.</p><p class="text-p">As the series progresses, the protagonists uncover dark secrets about the Titans and the history of their world. They learn that Titans are actually transformed humans and that their walled society has a complex and oppressive history. The story delves into the nature of power, freedom, and the moral ambiguity of war.</p><p class="text-p">Key arcs in the series include:</p><ul><li><p class="text-p"><strong class="text-strong">The Fall of Wall Maria</strong>: The story begins with the Titans breaching Wall Maria, leading to a desperate fight for survival and the beginning of Eren, Mikasa, and Armin’s journey.</p></li><li><p class="text-p"><strong class="text-strong">The Female Titan Arc</strong>: The protagonists discover that one of their own soldiers, Annie Leonhart, is the Female Titan, leading to a confrontation that reveals more about the Titan powers and the enemy\'s motives.</p></li><li><p class="text-p"><strong class="text-strong">The Battle of Trost District</strong>: A major battle where the protagonists face off against Titans within the city, highlighting their struggles and the dire situation of humanity.</p></li><li><p class="text-p"><strong class="text-strong">The Marley Arc</strong>: The story shifts focus to the nation of Marley, where it is revealed that the world is much larger and more complex than initially thought. This arc introduces new characters and explores the political landscape of the world outside the walls.</p></li><li><p class="text-p"><strong class="text-strong">The War for Paradis</strong>: The final arc brings intense conflict between the remaining inhabitants of Paradis Island and the forces of Marley. The protagonists confront their enemies, their own inner demons, and the harsh truths about their world’s history.</p></li></ul><p class="text-p">Throughout its run, "Attack on Titan" is known for its complex characters, unpredictable plot twists, and exploration of themes such as the nature of freedom, the cycle of hatred, and the cost of war. It provides a gripping and often brutal examination of humanity\'s fight for survival in the face of overwhelming odds.</p><p class="text-p">The series has been highly influential and is celebrated for its unique take on the post-apocalyptic genre, making it a standout in modern manga and anime.</p></body></html>',
        cover: {
          id: 24,
          name: "882932.jpg",
          alternativeText: null,
          caption: null,
          width: 667,
          height: "1970-01-01T07:30:01+07:30",
          formats: {
            small: {
              ext: ".jpg",
              url: "/uploads/small_882932_c630424466.jpg",
              hash: "small_882932_c630424466",
              mime: "image/jpeg",
              name: "small_882932.jpg",
              path: null,
              size: 48.45,
              width: 334,
              height: 500,
              sizeInBytes: 48454,
            },
            medium: {
              ext: ".jpg",
              url: "/uploads/medium_882932_c630424466.jpg",
              hash: "medium_882932_c630424466",
              mime: "image/jpeg",
              name: "medium_882932.jpg",
              path: null,
              size: 95.58,
              width: 500,
              height: 750,
              sizeInBytes: 95583,
            },
            thumbnail: {
              ext: ".jpg",
              url: "/uploads/thumbnail_882932_c630424466.jpg",
              hash: "thumbnail_882932_c630424466",
              mime: "image/jpeg",
              name: "thumbnail_882932.jpg",
              path: null,
              size: 6.75,
              width: 104,
              height: 156,
              sizeInBytes: "1970-01-01T07:30:06+07:30",
            },
          },
          hash: "882932_c630424466",
          ext: ".jpg",
          mime: "image/jpeg",
          size: 123.41,
          url: "/uploads/882932_c630424466.jpg",
          previewUrl: null,
          provider: "local",
          provider_metadata: null,
          folderPath: "/",
        },
      },
      {
        id: 9,
        title: "Naruto: Shippuden",
        author: "Masashi Kishimoto",
        publication: "2007-01-01T00:00:00+08:00",
        genre: "Action",
        ratings: 9,
        summary:
          '<html><head></head><body><p class="text-p"><strong class="text-strong">"Naruto: Shippuden"</strong> picks up where the original "Naruto" series left off, with Naruto Uzumaki returning to his village, Konohagakure, after training with the legendary ninja Jiraiya. Now a more skilled and mature ninja, Naruto\'s focus is on rescuing his friend and rival, Sasuke Uchiha, who has left the village to gain power from the dark ninja Orochimaru.</p><p class="text-p">The series delves into Naruto’s continued journey, exploring deeper themes of friendship, loss, and personal growth. It introduces new characters and organizations, most notably the Akatsuki, a group of rogue ninjas with their own sinister agenda. The Akatsuki are on a quest to capture all the Tailed Beasts, including Kurama, the demon fox sealed inside Naruto.</p><p class="text-p">The plot is divided into several arcs, including:</p><ul><li><p class="text-p"><strong class="text-strong">The Search for Sasuke</strong>: Naruto and his friends embark on missions to locate and bring back Sasuke, who is determined to gain power to avenge his family’s massacre.</p></li><li><p class="text-p"><strong class="text-strong">The Akatsuki’s Ambitions</strong>: The series reveals the Akatsuki’s plans to gather the Tailed Beasts and the threat they pose to the world. This arc involves significant battles and alliances between the ninja villages.</p></li><li><p class="text-p"><strong class="text-strong">The Fourth Great Ninja War</strong>: A major conflict arises as the Akatsuki’s leader, Obito Uchiha, and other villains launch a full-scale war against the ninja world. The war arc features intense battles, revelations about the characters\' pasts, and major plot twists.</p></li><li><p class="text-p"><strong class="text-strong">The Final Showdown</strong>: The story culminates in the final battle between Naruto and his greatest rival, Sasuke, as they confront their pasts and decide the future of their world.</p></li></ul><p class="text-p">"Naruto: Shippuden" expands on the original series\' world, offering more complex storylines, deeper character development, and higher stakes. It explores themes of redemption, the cycle of hatred, and the power of hope. The series concludes with a resolution to the conflicts introduced throughout Naruto\'s journey, marking a significant evolution in both the character and the narrative.</p><p class="text-p">Overall, "Naruto: Shippuden" is celebrated for its epic scope, emotional depth, and intricate storytelling, solidifying its place as a major work in the anime and manga world.</p></body></html>',
        cover: {
          id: 22,
          name: "828389.jpeg",
          alternativeText: null,
          caption: null,
          width: "1970-01-01T07:30:01+07:30",
          height: "1970-01-01T07:30:02+07:30",
          formats: {
            large: {
              ext: ".jpeg",
              url: "/uploads/large_828389_7f69f52fee.jpeg",
              hash: "large_828389_7f69f52fee",
              mime: "image/jpeg",
              name: "large_828389.jpeg",
              path: null,
              size: 171.93,
              width: 667,
              height: "1970-01-01T07:30:01+07:30",
              sizeInBytes: 171933,
            },
            small: {
              ext: ".jpeg",
              url: "/uploads/small_828389_7f69f52fee.jpeg",
              hash: "small_828389_7f69f52fee",
              mime: "image/jpeg",
              name: "small_828389.jpeg",
              path: null,
              size: 55.05,
              width: 333,
              height: 500,
              sizeInBytes: 55046,
            },
            medium: {
              ext: ".jpeg",
              url: "/uploads/medium_828389_7f69f52fee.jpeg",
              hash: "medium_828389_7f69f52fee",
              mime: "image/jpeg",
              name: "medium_828389.jpeg",
              path: null,
              size: 108.35,
              width: 500,
              height: 750,
              sizeInBytes: 108353,
            },
            thumbnail: {
              ext: ".jpeg",
              url: "/uploads/thumbnail_828389_7f69f52fee.jpeg",
              hash: "thumbnail_828389_7f69f52fee",
              mime: "image/jpeg",
              name: "thumbnail_828389.jpeg",
              path: null,
              size: 7.46,
              width: 104,
              height: 156,
              sizeInBytes: "1970-01-01T07:30:07+07:30",
            },
          },
          hash: "828389_7f69f52fee",
          ext: ".jpeg",
          mime: "image/jpeg",
          size: 531.54,
          url: "/uploads/828389_7f69f52fee.jpeg",
          previewUrl: null,
          provider: "local",
          provider_metadata: null,
          folderPath: "/",
        },
      },
      {
        id: 8,
        title: "Naruto",
        author: "Masashi Kishimoto",
        publication: "1999-01-01T00:00:00+08:00",
        genre: "Action",
        ratings: 9,
        summary:
          '<html><head></head><body><p class="text-p"><strong class="text-strong">"Naruto"</strong> follows the story of Naruto Uzumaki, a young ninja with a dream of becoming the strongest ninja and earning the respect of his village, Konohagakure. Naruto is an orphan who grew up with a powerful demon fox, Kurama, sealed inside him. This has led to him being shunned and isolated by the villagers who fear the demon within him.</p><p class="text-p">Despite the prejudice he faces, Naruto is determined to prove his worth and become the Hokage, the leader of his village. The series explores his journey from a mischievous and often misunderstood child to a respected and powerful ninja. Along the way, Naruto forms bonds with his friends and fellow ninjas, including Sasuke Uchiha and Sakura Haruno, who become his teammates in the pursuit of his goals.</p><p class="text-p">The story is divided into two parts: the original "Naruto" series and its sequel, "Naruto: Shippuden." In the original series, Naruto and his friends undertake various missions, face numerous challenges, and battle enemies who threaten their world. The sequel, "Naruto: Shippuden," continues the story as Naruto and his allies confront more dangerous foes and delve deeper into complex themes such as friendship, rivalry, and destiny.</p><p class="text-p">Throughout the series, Naruto’s growth as a ninja and as a person is central to the plot. He learns about the nature of true strength, the value of perseverance, and the importance of understanding and accepting others. The series also explores the backstories of other characters, their struggles, and their development.</p><p class="text-p">"Naruto" is renowned for its intricate world-building, diverse cast of characters, and engaging storylines. It combines action-packed sequences with emotional depth, making it a beloved and influential series in the world of manga and anime.</p></body></html>',
        cover: {
          id: 21,
          name: "882384.jpg",
          alternativeText: null,
          caption: null,
          width: "1970-01-01T07:30:01+07:30",
          height: "1970-01-01T07:30:02+07:30",
          formats: {
            large: {
              ext: ".jpg",
              url: "/uploads/large_882384_754ee9d165.jpg",
              hash: "large_882384_754ee9d165",
              mime: "image/jpeg",
              name: "large_882384.jpg",
              path: null,
              size: 224.54,
              width: 667,
              height: "1970-01-01T07:30:01+07:30",
              sizeInBytes: 224542,
            },
            small: {
              ext: ".jpg",
              url: "/uploads/small_882384_754ee9d165.jpg",
              hash: "small_882384_754ee9d165",
              mime: "image/jpeg",
              name: "small_882384.jpg",
              path: null,
              size: 66.06,
              width: 333,
              height: 500,
              sizeInBytes: 66061,
            },
            medium: {
              ext: ".jpg",
              url: "/uploads/medium_882384_754ee9d165.jpg",
              hash: "medium_882384_754ee9d165",
              mime: "image/jpeg",
              name: "medium_882384.jpg",
              path: null,
              size: 137.85,
              width: 500,
              height: 750,
              sizeInBytes: 137851,
            },
            thumbnail: {
              ext: ".jpg",
              url: "/uploads/thumbnail_882384_754ee9d165.jpg",
              hash: "thumbnail_882384_754ee9d165",
              mime: "image/jpeg",
              name: "thumbnail_882384.jpg",
              path: null,
              size: 7.73,
              width: 104,
              height: 156,
              sizeInBytes: "1970-01-01T07:30:07+07:30",
            },
          },
          hash: "882384_754ee9d165",
          ext: ".jpg",
          mime: "image/jpeg",
          size: 449.37,
          url: "/uploads/882384_754ee9d165.jpg",
          previewUrl: null,
          provider: "local",
          provider_metadata: null,
          folderPath: "/",
        },
      },
      {
        id: 5,
        title: "Wolverine: Weapon X Omnibus",
        author: "Barry Windsor-Smith",
        publication: "1991-09-03T00:00:00+08:00",
        genre: "Superhero",
        ratings: 9,
        summary:
          '<html><head></head><body><p class="text-p">The <em>Wolverine: Weapon X Omnibus</em> collects and expands on one of the most influential and gritty stories in Wolverine\'s history, focusing on the Weapon X program—a top-secret government project responsible for turning Logan into the Wolverine we know today.</p><p class="text-p">At the core of the <em>Weapon X</em> story is Logan, a man with incredible regenerative abilities and heightened senses, who is captured by a secret Canadian government organization. Logan undergoes a series of brutal and inhumane experiments that bond unbreakable adamantium metal to his skeleton, turning him into the ultimate killing machine. The scientists involved in Weapon X strip Logan of his humanity, reducing him to nothing more than a mindless weapon controlled by their programming.</p><p class="text-p">This transformation is a key part of Wolverine’s backstory, and it is during this time that he adopts the codename "Weapon X." As part of the program, Logan\'s natural mutant abilities are exploited and enhanced, making him virtually indestructible. However, the Weapon X program isn\'t just about giving Logan claws—it’s about completely erasing his identity, leaving him as a savage, animalistic force.</p><p class="text-p">As Logan endures psychological and physical torture, his memories are tampered with, leaving him a shell of his former self, confused and unable to distinguish reality from nightmare. His mind is fragmented, filled with violent and surreal visions, making it impossible for him to recall his past life. As time passes, Logan begins to fight back against his captors, slowly regaining control over his mind and escaping from the clutches of the program.</p><p class="text-p">The <em>Weapon X</em> storyline is a pivotal moment in Wolverine’s character development, explaining how he became the tortured and enigmatic hero seen throughout Marvel Comics. The brutal conditioning he underwent explains his deep sense of rage, isolation, and the inner struggle he constantly faces between man and beast. It also sets the stage for many of the conflicts and relationships Wolverine has with other characters in the Marvel universe, particularly in relation to his quest for self-discovery and revenge against those responsible for turning him into a weapon.</p><p class="text-p"><strong class="text-strong">Additional Content in the Omnibus</strong>: The <em>Wolverine: Weapon X Omnibus</em> includes the original <em>Weapon X</em> story, along with a range of other issues that explore different aspects of Wolverine’s history and involvement with the program. These stories delve deeper into the ethical and moral implications of the Weapon X program, as well as its wider impact on the Marvel Universe. You may also find stories that expand on other characters who were part of the program or influenced by it.</p><p class="text-p"><strong class="text-strong">Themes</strong>:</p><ul><li><p class="text-p"><strong class="text-strong">Identity</strong>: The story deals heavily with Logan’s lost identity and the question of what it means to be human versus being a weapon.</p></li><li><p class="text-p"><strong class="text-strong">Memory and Trauma</strong>: Logan\'s fractured memories and struggle to reclaim his past after being subjected to intense psychological manipulation is a recurring theme.</p></li><li><p class="text-p"><strong class="text-strong">Experimentation and Control</strong>: The Weapon X program represents the darker side of scientific ambition, focusing on the idea of controlling nature through extreme means.</p></li><li><p class="text-p"><strong class="text-strong">Savage vs. Civilized</strong>: Wolverine is often portrayed as someone who walks the line between a savage beast and a disciplined man, with the Weapon X program exacerbating this internal conflict.</p></li></ul><p class="text-p"><strong class="text-strong">Artwork</strong>: Barry Windsor-Smith’s art in <em>Weapon X</em> is highly detailed, gritty, and often surreal, perfectly capturing the psychological torment Logan endures. The visuals are dark, violent, and claustrophobic, amplifying the horror of Wolverine\'s transformation. The mechanical, sterile world of the Weapon X lab contrasts sharply with Logan\'s feral nature, adding to the story’s tension.</p><p class="text-p"><strong class="text-strong">Impact</strong>: The <em>Weapon X</em> storyline became one of the definitive Wolverine arcs, laying the foundation for many future stories involving his origins, his ties to the government, and the moral questions surrounding his use as a weapon. This omnibus is essential reading for anyone who wants to understand the complex history of Wolverine and the deep psychological scars he carries.</p></body></html>',
        cover: {
          id: 18,
          name: "92139812.jpg",
          alternativeText: null,
          caption: null,
          width: 680,
          height: "1970-01-01T07:30:01+07:30",
          formats: {
            small: {
              ext: ".jpg",
              url: "/uploads/small_92139812_393a9d480b.jpg",
              hash: "small_92139812_393a9d480b",
              mime: "image/jpeg",
              name: "small_92139812.jpg",
              path: null,
              size: 43.39,
              width: 340,
              height: 500,
              sizeInBytes: 43385,
            },
            medium: {
              ext: ".jpg",
              url: "/uploads/medium_92139812_393a9d480b.jpg",
              hash: "medium_92139812_393a9d480b",
              mime: "image/jpeg",
              name: "medium_92139812.jpg",
              path: null,
              size: 80.94,
              width: 510,
              height: 750,
              sizeInBytes: 80945,
            },
            thumbnail: {
              ext: ".jpg",
              url: "/uploads/thumbnail_92139812_393a9d480b.jpg",
              hash: "thumbnail_92139812_393a9d480b",
              mime: "image/jpeg",
              name: "thumbnail_92139812.jpg",
              path: null,
              size: 6.56,
              width: 106,
              height: 156,
              sizeInBytes: "1970-01-01T07:30:06+07:30",
            },
          },
          hash: "92139812_393a9d480b",
          ext: ".jpg",
          mime: "image/jpeg",
          size: 97.17,
          url: "/uploads/92139812_393a9d480b.jpg",
          previewUrl: null,
          provider: "local",
          provider_metadata: null,
          folderPath: "/",
        },
      },
      {
        id: 7,
        title: "Spider-Man: Get Kraven",
        author: "J.M. DeMatteis",
        publication: "1985-02-01T00:00:00+08:00",
        genre: "Superhero",
        ratings: 9,
        summary:
          '<html><head></head><body><p class="text-p">In "Spider-Man: Get Kraven," the story centers around Kraven the Hunter, a notorious villain in the Spider-Man universe known for his obsession with proving himself as the ultimate hunter. The plot begins with Kraven setting a trap for Spider-Man, driven by his desire to capture and defeat him to cement his status as the greatest hunter of all time.</p><p class="text-p">Kraven, who has always considered Spider-Man a worthy prey, devises an elaborate plan to outwit and overpower him. His strategy involves a series of meticulously planned encounters designed to wear Spider-Man down physically and mentally. Kraven\'s obsession with Spider-Man becomes the central focus of the narrative, revealing the depths of his fixation and the lengths he will go to achieve his goal.</p><p class="text-p">As the story unfolds, Spider-Man finds himself increasingly cornered and challenged by Kraven\'s relentless pursuit. The hero is forced to confront not only the physical threats posed by Kraven but also the psychological warfare that comes with being hunted. The conflict takes a toll on Spider-Man, testing his endurance, resourcefulness, and resolve.</p><p class="text-p">Throughout the graphic novel, there is a significant exploration of Kraven\'s character. The story delves into his background, motivations, and the inner workings of his mind. It becomes clear that Kraven\'s obsession is driven by more than just a desire for victory; it’s also about proving himself in a way that goes beyond mere physical prowess. His pursuit of Spider-Man is a reflection of his own insecurities and his need for validation.</p><p class="text-p">As Spider-Man grapples with the mounting pressure and the escalating danger, he must find a way to outsmart Kraven and turn the tables on his relentless pursuer. The narrative builds to a dramatic climax, showcasing Spider-Man’s resilience and ingenuity in overcoming one of his most formidable adversaries.</p><p class="text-p">"Spider-Man: Get Kraven" is a gripping tale of obsession, strategy, and the enduring battle between hero and villain. It highlights the psychological aspects of the characters and provides an intense and engaging experience for readers, offering a deeper look into the complexities of both Spider-Man and Kraven the Hunter.</p></body></html>',
        cover: {
          id: 20,
          name: "9192993.jpg",
          alternativeText: null,
          caption: null,
          width: 631,
          height: "1970-01-01T07:30:01+07:30",
          formats: {
            small: {
              ext: ".jpg",
              url: "/uploads/small_9192993_99678b5744.jpg",
              hash: "small_9192993_99678b5744",
              mime: "image/jpeg",
              name: "small_9192993.jpg",
              path: null,
              size: 50.68,
              width: 316,
              height: 500,
              sizeInBytes: 50677,
            },
            medium: {
              ext: ".jpg",
              url: "/uploads/medium_9192993_99678b5744.jpg",
              hash: "medium_9192993_99678b5744",
              mime: "image/jpeg",
              name: "medium_9192993.jpg",
              path: null,
              size: 96.08,
              width: 473,
              height: 750,
              sizeInBytes: 96084,
            },
            thumbnail: {
              ext: ".jpg",
              url: "/uploads/thumbnail_9192993_99678b5744.jpg",
              hash: "thumbnail_9192993_99678b5744",
              mime: "image/jpeg",
              name: "thumbnail_9192993.jpg",
              path: null,
              size: 7,
              width: 98,
              height: 156,
              sizeInBytes: "1970-01-01T07:30:06+07:30",
            },
          },
          hash: "9192993_99678b5744",
          ext: ".jpg",
          mime: "image/jpeg",
          size: 120.63,
          url: "/uploads/9192993_99678b5744.jpg",
          previewUrl: null,
          provider: "local",
          provider_metadata: null,
          folderPath: "/",
        },
      },
    ];

    const { id } = req.params; // Capture the id from the route parameters

    if (id) {
      // Fetch a single novel by ID
      const novel = novels.find((n) => n.id === parseInt(id));

      if (!novel) {
        return res.status(404).json({ error: `Novel with ID ${id} not found` });
      }

      return res.status(200).json({ data: novel });
    }

    // If no ID is provided, return all novels
    res.status(200).json({ data: novels });
  } catch (error) {
    res
      .status(500)
      .json({ error: "Failed to fetch novels", details: error.message });
  }
};
